package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"fmt"

	"github.com/johannessarpola/graphql-test/graph/model"
)

// AddItemsToPlaylist is the resolver for the addItemsToPlaylist field.
func (r *mutationResolver) AddItemsToPlaylist(ctx context.Context, input model.AddItemsToPlaylistInput) (*model.AddItemsToPlaylistPayload, error) {
	panic(fmt.Errorf("not implemented: AddItemsToPlaylist - addItemsToPlaylist"))
}

// FeaturedPlaylists is the resolver for the featuredPlaylists field.
func (r *queryResolver) FeaturedPlaylists(ctx context.Context) ([]*model.Playlist, error) {
	panic(fmt.Errorf("not implemented: FeaturedPlaylists - featuredPlaylists"))
}

// Playlist is the resolver for the playlist field.
func (r *queryResolver) Playlist(ctx context.Context, id string) (*model.Playlist, error) {
	panic(fmt.Errorf("not implemented: Playlist - playlist"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
