// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddItemsToPlaylistInput struct {
	// The ID of the playlist.
	PlaylistID string `json:"playlistId"`
	// A comma-separated list of Spotify URIs to add.
	Uris []string `json:"uris"`
}

type AddItemsToPlaylistPayload struct {
	// Similar to HTTP status code, represents the status of the mutation
	Code int `json:"code"`
	// Indicates whether the mutation was successful
	Success bool `json:"success"`
	// Human-readable message for the UI
	Message string `json:"message"`
	// The playlist that contains the newly added items
	Playlist *Playlist `json:"playlist,omitempty"`
}

type Mutation struct {
}

// A curated collection of tracks designed for a specific activity or mood.
type Playlist struct {
	// The ID for the playlist.
	ID string `json:"id"`
	// The name of the playlist.
	Name string `json:"name"`
	// Describes the playlist, what to expect and entices the user to listen.
	Description *string `json:"description,omitempty"`
	// The tracks of the playlist.
	Tracks []*Track `json:"tracks"`
}

type Query struct {
}

// A single audio file, usually a song.
type Track struct {
	// The ID for the track.
	ID string `json:"id"`
	// The name of the track
	Name string `json:"name"`
	// The track length in milliseconds.
	DurationMs int `json:"durationMs"`
	// Whether or not the track has explicit lyrics (true = yes it does; false = no it does not OR unknown)
	Explicit bool `json:"explicit"`
	// The URI for the track, usually a Spotify link.
	URI string `json:"uri"`
}
